<a href="https://colab.research.google.com/github/jeurginocode/introductionupb202410/blob/main/librerias_numpy_archivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy
mas informacion:
[Numpy](https://numpy.org/devdocs/user/absolute_beginners.html#welcome-to-numpy)

**Python list vs NumPy array**

*   Mientras que en las listas podemos tener diferentes tipos de datos, en
NumPy los arrays deben ser homogéneos.
*   Los *arrays* en NumPy son más rápidos y compactos que las *listas*.
Consumen menos memoria y se puede especificar su tipo de datos

##arrays:
Es basicaementeun tipo especial de lista usualmente utilizada para almacenar
números debido a que facilita la ejecución de operaciones matemáticas
que son sencillas de escribir y más eficientes computacionalmente.

###carateristicas

*   Es la estructura de datos central de la librería NumPy
*  Es una matriz de valores que contiene información sobre datos sin
procesar, cómo ubicar un elemento y cómo interpretarlo
Sus elementos pueden ser indexados y son del mismo tipo (`dtype`).
*   Puede ser indexado por una tupla de enteros no negativos, booleanos,
otro array o enteros.
*   El rango (`rank`) de un array es el número de dimensiones.
*   La forma (`shape`) del array es una tupla de enteros que dan el tamaño
del array en cada dimensión.
*   Podemos inicializar un array a partir de una lista (o varias para más
dimensiones).
###Array from CSV
Normalmente no ingresamos datos directamente en un array. En lugar
de esto, importamos los datos de otro lugar.\
Podemos transformar archivos CSV en arrays usando la función
`np.genfromtxt()`:


```
recipes= np.genfromtxt("/content/recipes.csv", delimiter=",")#no.genformtxt# trasnsforma achivos CSV en arrasys
print(recipes)
>>>[[2.    0.75  2.    1.    0.5  ]
>>>[1.    0.125 1.    1.    0.125]
>>>[2.75  1.5   1.    0.    1.   ]
>>>[4.    0.5   2.    2.    0.5  ]]
```



In [1]:

#la didfenrecia entre lista y arrays es que los arrasy son mas rapidos, y que cuando se imprime es sin la comas
[]
import numpy as np

edades=[18, 17, 18, 17, 24, 16, 17, 23, 19, 15, 15]
edades_array = np.array(edades)
# print(edades)#imprime sin comas
# print(edades_array)
# pirnt(edades_arrat.dtype)


birt_years=[]
for edad in edades:
  birt_years.append(2024-edad)
  print(birt_years)

birth_years_array = 2024-edades_array
print(birth_years_array)

[2006]
[2006, 2007]
[2006, 2007, 2006]
[2006, 2007, 2006, 2007]
[2006, 2007, 2006, 2007, 2000]
[2006, 2007, 2006, 2007, 2000, 2008]
[2006, 2007, 2006, 2007, 2000, 2008, 2007]
[2006, 2007, 2006, 2007, 2000, 2008, 2007, 2001]
[2006, 2007, 2006, 2007, 2000, 2008, 2007, 2001, 2005]
[2006, 2007, 2006, 2007, 2000, 2008, 2007, 2001, 2005, 2009]
[2006, 2007, 2006, 2007, 2000, 2008, 2007, 2001, 2005, 2009, 2009]
[2006 2007 2006 2007 2000 2008 2007 2001 2005 2009 2009]


In [ ]:
m= np.array([32, 27,3,8,],
            [1,2,3,4],
            [1,2,5,6,7])
print(m)
print(m.shape)
print(m[1][0])

print(a[3])
print()


In [ ]:

edades=[18, 17, 18, 17, 24, 16, 17, 23, 19, 15, 15]
edades_array = np.array(edades)
edades_pares= edades_array[edades_array % 2== 0]
mayores_de_edades= edades_array >= 18
eadades_5 = edades_array[edades_array ]

IndexError: index 18 is out of bounds for axis 0 with size 11

In [ ]:
import numpy as np

recipes= np.genfromtxt("/content/recipes.csv", delimiter=",")#no.genformtxt# trasnsforma achivos CSV en arrasys
print(recipes)

# print(recipes.dtype)
# print(recipes.dtype)
# print(recipes.shape)

# eggs=recipes[:, 2]
# print(eggs[eggs==1])

# cupcackes=2*recipes[0,:]
# cookies= recipes[2, :]

# grocery_list=cupcackes+cookies
# print(grocery_list)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


In [ ]:
nj_10=np.arange(10)
print(nj_10)
n_5_20_3=np.arange(5, 20, 3)
print(n_5_20_3)

t=np.linspace(0, 2*np.pi,num=10)
print(t)


[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [ ]:
vector_9=np.arange(9)
print(vector_9)


n =np.arenge(10,20)
print(n)
print(n.sum())

[0 1 2 3 4 5 6 7 8]


In [9]:
a=np.arange(0,10)
b=np.arange(10,20)

matrix_h = np.array([1, 2, 3, 4, 5])
print(matrix_h)
print(f"suma de todos los valores: {matrix_h.sum()}")#axis seleccioan el eje que v asumasr en columan o fila
print(f"suma de las columnas{matrix_h.sum(0)}")

[1 2 3 4 5]
suma de todos los valores: 15
suma de las columnas15


In [ ]:
rng=np.random.default_rng()
rand_1= rng.integers(_10, 10)

##NumPy fpr linear Algebra operations

In [ ]:
A = np.array([[1,2],[3,4]])

print(A,"\n")
print(4*A, "\n")

B=np.ones(shape = [2,2])

print(A)


[[1 2]
 [3 4]] 

[[ 4  8]
 [12 16]] 

[[1 2]
 [3 4]]


##estadistica basicas en numpy

In [5]:
# crear hacer el primedio e las siguinetres array




array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# promedio_array1 = np.mean(array1)
# promedio_array2 = np.mean(array2)
# print("El promedio del primer array es:", promedio_array1)
# print("El promedio del segundo array es:", promedio_array2)

# ring_toss= np.array([[1,0,0],
#                     [0,0,1],
#                     [1,0,1]])
# print(np.mean(ring_toss))
# print(np.mean(ring_toss, axis=1))
# print(np.mean(ring_toss, axis=0))


allergy_trails=np.array([[6,1,3,8,2],[2,6,3,9,8],[5,2,6,9,9]])

# pruebas = int
# for prueba in pruebas:
total_medai= np.array(allergy_trails)
print(np.mean(allergy_trails))
print(np.mean(allergy_trails, axis=1))
print(np.mean(allergy_trails, axis=0))

5.266666666666667
[4.  5.6 6.2]
[4.33333333 3.         4.         8.66666667 6.33333333]


Otra métrica importante que podemos utilizar en análisis de datos es la
media. Este es el valor que se encuentra en el centro de todos los datos
al ser ordenados en términos de su magnitud (de menor a mayor).
Podemos calcular la mediana con la función `np.median`:

In [10]:
# mediana
my_array = np.array ([50, 38, 291, 59, 14])
print(np.median(my_array))

50.0


* La mediana

es el valor que se ubica en el centro de un conjunto de
datos, es decir, el número para el cual el 50% de los datos están por
encima y el otro 50% por debajo.
Un percentil es un punto que me divide la distribución tal que un
porcentaje se encuentra por debajo de este. Por ejemplo. El percentil
40vo indica que el 40% de los datos se encuentran por debajo de este, y
el 60% por encima.

En NumPy podemos calcular percentiles usando la función
`np.percentile`, la cual toma dos argumentos: el array y el percentil
a calcular:

In [11]:
# percemtiles
d = np.array([6, 8, 3, 4, 4, 4, 6, 7, 5, 8, 8])
print(np.percentile (d, 40))

5.0


##NumPy for Linear Algebra – linalg


In [ ]:
A = np.array([[1,2],[3,4]])
# B=np.ones(2, dtype=np)


b=np.array([[5],[10]])
A_inv= np.linalg.inv(A)

print(A)
# pirn(A_inv)
# pint(np.eye(2))
# print(A @ A_inv)

x= A_inv @ A
print(b)

[[1 2]
 [3 4]]
[[ 5]
 [10]]


#tarea
hacer un algoritmo que use el maximo y el minimo de un matriz sin la fucione de numpy



```
A = ([[1,2],[3,4]])
new_A=[]
 for row ina A:
  temp_row =[
     for element in row:
      tme_row.append(4 *element)
     new_A.append(temp_row)
print(A)
print(new_A)
```



In [ ]:
A = ([[1,2],[3,4]])
new_A=[]
for row in A:
  temp_row =[]
  for element in row:
    temp_row.append(4 *element)
    temp_ro
    new_A.append(temp_row)
print(A)
print("--------")
print(new_A)