<a href="https://colab.research.google.com/github/jeurginocode/introductionupb202410/blob/main/librerias_numpy_archivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy
#la didfenreci entre lista y arrays es que los arrasy son mas rapidos, y que cuando se imprime es sin la comas
import numpy as np

edades=[18, 17, 18, 17, 24, 16, 17, 23, 19, 15, 15]
edad_arrat = np.array(edades)
# print(edades)#imprime sin coams
# print(edades_array)
# pirnt(edades_arrat.dtype)


birt_years=[]
for edad in edades:birt_years.append():
  años_nacimiento.append(2024-edad)
print(años_nacimiento)


In [ ]:
m= np.array([32, 27,3,8,],[1,2,3,4],[1,2,5,6,7])
print(m)
print(m.shape)

print(a[3])
print()


In [ ]:
edades=[18, 17, 18, 17, 24, 16, 17, 23, 19, 15, 15]
edad_array = np.array(edades)
eadedes_pares= edad_array[edad_array % 2= 0]
eadades_5 = edad_array[edad_array ]

In [7]:
import numpy as np

recipes= np.genfromtxt("/content/recipes.csv", delimiter=",")
# print(recipes)

# print(recipes.dtype)
# print(recipes.dtype)
# print(recipes.shape)

eggs=recipes[:, 2]
print(eggs[eggs==1])

cupcackes=2*recipes[0,:]
cookies= recipes[2, :]

grocery_list=cupcackes+cookies
print(grocery_list)

[1. 1.]
[6.75 3.   5.   2.   2.  ]


In [10]:
nj_10=np.arange(10)
print(nj_10)
n_5_20_3=np.arange(5, 20, 3)
print(n_5_20_3)

t=np.linspace(0, 2*np.pi,num=10)
print(t)


[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [12]:
vector_9=np.arange(9)
print(vector_9)


n =np.arenge(10,20)
print(n)
print(n.sum())

[0 1 2 3 4 5 6 7 8]


In [ ]:
a=np.arnege(0,10)
b=np.arange(10,20)

matrix
print(matrix_h)
print(f"suma de todos los valores: {matriz_h.sum()}")#axis seleccioan el eje que v asumasr en columan o fila
print(f"suma de las columnas{matri_h.sum(0)}")

In [ ]:
rng=np.random.default_rng()
rand_1= rng.integers(_10, 10)