<a href="https://colab.research.google.com/github/jeurginocode/introductionupb202410/blob/main/librerias_numpy_archivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy
mas informacion:
[Numpy](https://numpy.org/devdocs/user/absolute_beginners.html#welcome-to-numpy)

**Python list vs NumPy array**

*   Mientras que en las listas podemos tener diferentes tipos de datos, en
NumPy los arrays deben ser homogéneos.
*   Los *arrays* en NumPy son más rápidos y compactos que las *listas*.
Consumen menos memoria y se puede especificar su tipo de datos

##arrays:
Es basicaementeun tipo especial de lista usualmente utilizada para almacenar
números debido a que facilita la ejecución de operaciones matemáticas
que son sencillas de escribir y más eficientes computacionalmente.

###carateristicas

*   Es la estructura de datos central de la librería NumPy
*  Es una matriz de valores que contiene información sobre datos sin
procesar, cómo ubicar un elemento y cómo interpretarlo
Sus elementos pueden ser indexados y son del mismo tipo (`dtype`).
*   Puede ser indexado por una tupla de enteros no negativos, booleanos,
otro array o enteros.
*   El rango (`rank`) de un array es el número de dimensiones.
*   La forma (`shape`) del array es una tupla de enteros que dan el tamaño
del array en cada dimensión.
*   Podemos inicializar un array a partir de una lista (o varias para más
dimensiones).
###Array from CSV
Normalmente no ingresamos datos directamente en un array. En lugar
de esto, importamos los datos de otro lugar.\
Podemos transformar archivos CSV en arrays usando la función
`np.genfromtxt()`:

In [5]:

#la didfenrecia entre lista y arrays es que los arrasy son mas rapidos, y que cuando se imprime es sin la comas
[]
import numpy as np

edades=[18, 17, 18, 17, 24, 16, 17, 23, 19, 15, 15]
edad_arrat = np.array(edades)
# print(edades)#imprime sin comas
# print(edades_array)
# pirnt(edades_arrat.dtype)


birt_years=[]
for edad in edades:
  birt_years.append(2024-edad)
print(birt_years)


[2006, 2007, 2006, 2007, 2000, 2008, 2007, 2001, 2005, 2009, 2009]


In [ ]:
m= np.array([32, 27,3,8,],[1,2,3,4],[1,2,5,6,7])
print(m)
print(m.shape)

print(a[3])
print()


In [ ]:
edades=[18, 17, 18, 17, 24, 16, 17, 23, 19, 15, 15]
edad_array = np.array(edades)
eadedes_pares= edad_array[edad_array % 2== 0]
eadades_5 = edad_array[edad_array ]

In [ ]:
import numpy as np

recipes= np.genfromtxt("/content/recipes.csv", delimiter=",")#no.genformtxt# trasnsforma achivos CSV en arrasys
# print(recipes)

# print(recipes.dtype)
# print(recipes.dtype)
# print(recipes.shape)

eggs=recipes[:, 2]
print(eggs[eggs==1])

cupcackes=2*recipes[0,:]
cookies= recipes[2, :]

grocery_list=cupcackes+cookies
print(grocery_list)

[1. 1.]
[6.75 3.   5.   2.   2.  ]


In [ ]:
nj_10=np.arange(10)
print(nj_10)
n_5_20_3=np.arange(5, 20, 3)
print(n_5_20_3)

t=np.linspace(0, 2*np.pi,num=10)
print(t)


[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [ ]:
vector_9=np.arange(9)
print(vector_9)


n =np.arenge(10,20)
print(n)
print(n.sum())

[0 1 2 3 4 5 6 7 8]


In [ ]:
a=np.arnege(0,10)
b=np.arange(10,20)

matrix
print(matrix_h)
print(f"suma de todos los valores: {matriz_h.sum()}")#axis seleccioan el eje que v asumasr en columan o fila
print(f"suma de las columnas{matri_h.sum(0)}")

In [ ]:
rng=np.random.default_rng()
rand_1= rng.integers(_10, 10)

#tarea
hacer un algoritmo que suq ele maximo y el minimo de un matriz sin la fucione de numpy